### ISSUE TITLE
Model and class indices for Release 0.4.0?

### ISSUE THREAD

**Issue by farazk86** [Thimira/bird_watch#7]
Hi,

Thank you for putting together this github repo, its a great asset for birdwatchers. I was wondering if you are planning on making model 0.4.0 available in releases for download? On your website you mentioned that it has better performance and supports more bird species. Do you plan on adding that to your github repo?

Thanks

**Comment by jodfie** [comment]
Sorry to bring up a closed issue but I wanted @farazk86 included as well.

First: this is awesome! And exactly what I was working on...

Second: is this still being developed @Thimira or @farazk86 ?

Third: instead of training my own model can I use the iNaturalist Tensorflow/TFLite model instead?

**Comment by Thimira** [comment]
@jodfie and @farazk86 
Thank you for your interest in the project.
I am in the process of rewriting some of the model architecture, and hope to release a new version within few weeks.

**Comment by jodfie** [comment]
Awesome! Can the iNaturalist one be subbed in? 

Also this will only take pictures uploaded via the flask site? Can it be automated as well from pictures captured by OpenCV?

**Comment by seanawesome** [comment]
Waiting on an update.
